### PR TITLE
Error index.js line 29

### PR DESCRIPTION
**Pull request by movitch**
Hi,

I try to use your plugin for jeedom. Thank you very much for this. There is a mistake in line 29 in index.js
 **this.humidtyCommandID ** ->  this.humidityCommandID

Mistake again in config sample :
"accessory": "**Httpjeedom**", -> "accessory": "HttpJeedom"

Bye

### CODE REVIEW

**Comment by rudders** [comment]
This if for the jeedom plugin fork maintained by @jude16. I can process it here. jude16 will need to open up that repo for PRs. Perhaps DM @jude16.

**Comment by movitch** [comment]
Sorry this is my first contribution in github. 
I hope not to have made ​​a mistake...

**Comment by rudders** [comment]
No problem at all - I just can't PR to that repo - only to my own! Just didn't want to offend you when I closed the PR without accepting it!

**Comment by movitch** [comment]
No problem. Thank you very much !

**Pull request closed without merging**
