### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by MrsDelish**
Added support for Motion, it has a string http response for ON/Active
it is now a easy way to turn on and off motion detection.

config.json
{
        "accessory": "Http",
        "name": "Motion Status",
        "switchHandling": "yes",
        "http_method": "GET",
        "on_url":      "http://localhost:8082/0/detection/start",
        "off_url":     "http://localhost:8082/0/detection/pause",
        "status_url":  "http://localhost:8082/0/detection/status",
        "service": "Switch",
        "brightnessHandling": "no",
        "brightness_url":     "",
        "brightnesslvl_url":  "",
        "sendimmediately": "",
        "username" : "",
        "password" : ""
      }

### CODE REVIEW

**Comment by NovaGL** [comment]
So basically this means if active then ACTIVE becomes 1?

**Comment by MrsDelish** [comment]
Yes, 
Thanks for a great plugin :-)
cheers

Here is the output from my "status_url": "http://localhost:8082/0/detection/status <http://localhost:8082/0/detection/status>",

motion returns the following html when detection is running
<!DOCTYPE html>
<html>
<head><title>Motion 4.0.1</title></head>
<body>
<a href=/0/detection>&lt;&ndash; back</a><br><br><b>Camera 0</b> Detection status ACTIVE
</body>
</html>

And this when detection is paused
<!DOCTYPE html>
<html>
<head><title>Motion 4.0.1</title></head>
<body>
<a href=/0/detection>&lt;&ndash; back</a><br><br><b>Camera 0</b> Detection status PAUSE
</body>
</html>

**Comment by NovaGL** [comment]
So have you done 0 for pause. Don't thank me I didn't make this, rudders did I'm just maintaining it

**Comment by MrsDelish** [comment]
A dedicated check for pause is not needed, I think. I can make one if you want.
It will return 0 if it is not active since the html response will be handled by the original check.

home.app will update the switch status both ways if I either manually start or stop motion, or click the switch ofc.

**Comment by NovaGL** [comment]
I think this should be fine

**Pull request merged**
