### PR TITLE
Door Control

### PR DESCRIPTION
**Pull request by NovaGL**
Latest version allows people to lock and unlock doors, it's very basic atm, its mainly meant for Doors with latches as it will default to locked when you go back into the app.

My doors don't provide status, so there is no way to test that so it always returns that the door is locked.

Sorry that it's not easy to be merged maybe I will start another repo if I have many more changes.

Not adding custom characteristics as they can't be called by Siri and only show in some apps.

```xml
"accessories": [ 
		{
            "accessory": "Http",
            "name": "Front Door",
             "service": "Lock"
                 "unlock_url": "http://localhost/unlock",
                 "lock_url": "http://localhost/lock",
	             "http_method": "GET",
			
	       }
    ]
```

### CODE REVIEW

**Comment by rudders** [comment]
I'm more than happy to replace the entire codebase with you repo mate or even assign this repo to you as you're advancing it nicely bur we need to decide if it's http or httpstatus ? if you can migrate back to http then we should retain backward compatibility with the original module. Equally we need to make sure it doesn't become very specify to your own setup and that it remains generic - the current checking of state for instance assumes a specific format or return value does' it?

**Comment by NovaGL** [comment]
1. Keep it HTTP, its your project, I just want to help you with it.
2. Would I then do a pull request from yours and add the changes again?
3. I would like to keep you the owner so we can make sure that it doesn't become to specific and retains generic.
4. It does not currently support getting status, it always returns locked, I have no way of doing that as I don't have one with status control. Just think of it as your initial switch.

**Comment by jnovack** [comment]
Personally, I like "HTTP" (all caps), but I understand that breaks compat just as much as "HttpStatus".

and now I hate you NovaGL, I revamped rudders' entire file with spacing and linting consistency.  #allfornothing. :p

**Comment by rudders** [comment]
We're in Australia dude - already 1/1 here and only 6am!

**Comment by NovaGL** [comment]
No need for hate, all friends here :)

If you would like @jnovack we can use your code for the basis of a new advanced Http plugin.

But we still need to come up on a consensus of name and what should and should not be included in this new plugin.

**Pull request closed without merging**
